### ISSUE TITLE
Announcements via popup on sync client

### ISSUE THREAD

**Issue by enricocanino** [owncloud/announcementcenter#25]
Hi and thank you for this usefull application.

As you are planning to enhance messaging to send to a certain user or goup, please think also about the possibility to generate a popup message on the remote Windows PCs that are running Sync Desktop Client...

Thank in advance...

Enrico

**Comment by nickvergessen** [comment]
Well that is already in progress. We use the notification app for that, which is part of the bundled download since 8.2
It may take one more client release cycle until it is implemented on the sync clients though, because 2.1 is almost done at this point.
https://github.com/owncloud/client/issues/3733
https://github.com/owncloud/core/issues/19152

**Comment by enricocanino** [comment]
OK... GREAT!

**Comment by nickvergessen** [comment]
Closing as per above and https://owncloud.org/blog/about-activities-and-notifications-in-owncloud/
